<?php

return [
'districts'=>[
		'Barguna' ,
		'Barisal' ,
		'Bhola' ,
		'Jhalokati' ,
		'Patuakhali' ,
		'Pirojpur' ,
		'Bandarban' ,
		'Brahmanbaria' ,
		'Chandpur' ,
		'Chittagong' ,
		'Comilla' ,
		'Coxs-Bazar' ,
		'Feni' ,
		'Khagrachhari' ,
		'Lakshmipur' ,
		'Noakhali' ,
		'Rangamati' ,
		'Dhaka' ,
		'Faridpur' ,
		'Gazipur' ,
		'Gopalganj' ,
		'Jamalpur' ,
		'Kishoreganj' ,
		'Madaripur' ,
		'Manikganj' ,
		'Munshiganj' ,
		'Mymensingh' ,
		'Narayanganj' ,
		'Narsingdi' ,
		'Netrakona' ,
		'Rajbari' ,
		'Shariatpur' ,
		'Sherpur' ,
		'Tangail' ,
		'Bagerhat' ,
		'Chuadanga' ,
		'Jessore' ,
		'Jhenaidah' ,
		'Khulna' ,
		'Kushtia' ,
		'Magura' ,
		'Meherpur' ,
		'Narail' ,
		'Satkhira' ,
		'Bogra' ,
		'Joypurhat' ,
		'Naogaon' ,
		'Natore' ,
		'Nawabganj' ,
		'Pabna' ,
		'Rajshahi' ,
		'Sirajganj' ,
		'Dinajpur' ,
		'Gaibandha' ,
		'Kurigram' ,
		'Lalmonirhat' ,
		'Nilphamari' ,
		'Panchagarh' ,
		'Rangpur' ,
		'Thakurgaon' ,
		'Habiganj' ,
		'Moulvibazar' ,
		'Sunamganj' ,
		'Sylhet' 
		],

];